
[build]
target = "core/frontend/index.html"
dist = "dist/"

[serve]
addresses = ["0.0.0.0"]
port = 8080
open = true

[watch]
ignore = [
	"Cargo.lock",
	"README.md",
	".gitignore",
	"target",
	"core/backend/"
]

[[proxy]]
rewrite = "/api"
backend = "http://127.0.0.1:8081"
