use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use sqlx::prelude::FromRow;


/// Model representation for uploads database schema.
#[derive(Serialize, Deserialize, FromRow, Debug, PartialEq, PartialOrd, Clone)]
pub struct Uploads {
	/// The primary key for this model.
	id: i32,

	/// The platform this was uploaded to.
	upload_platform_id: i32,
	
	/// The run this upload belongs to.
	run_id: i32,

	/// The URL generated by the upload platform provider.
	generated_url: i32,

	/// When was this uploaded.
	uploaded_at: DateTime<Utc>
}
