use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use sqlx::prelude::FromRow;


/// Model representation for uploads database schema.
#[derive(Serialize, Deserialize, FromRow, Debug, PartialEq, PartialOrd, Clone)]
pub struct Uploads {
	/// The primary key for this model.
	id: i32,

	/// The platform this was uploaded to.
	upload_platform_id: i32,
	
	/// The run this upload belongs to.
	run_id: i32,

	/// The URL generated by the upload platform provider.
	generated_url: i32,

	/// When was this uploaded.
	uploaded_at: DateTime<Utc>
}

impl Uploads {
	/// The primary key for this model.
    pub fn id(&self) -> i32 {
        self.id
    }

	/// The platform this was uploaded to.
    pub fn upload_platform_id(&self) -> i32 {
        self.upload_platform_id
    }

	/// The run this upload belongs to.
    pub fn run_id(&self) -> i32 {
        self.run_id
    }

	/// The URL generated by the upload platform provider.
    pub fn generated_url(&self) -> i32 {
        self.generated_url
    }

	/// When was this uploaded.
    pub fn uploaded_at(&self) -> DateTime<Utc> {
        self.uploaded_at
    }
}
