[package]
name = "backend"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4.11.0"
dyn_path = "1.0.7"
flexi_logger = "0.31.2"
log = "0.4.27"
reqwest = "0.12.23"
serde = { version = "1.0.219", features = ["derive"] }
thiserror = "2.0.16"
