services:
  reddyt-main:
    container_name: reddyt
    build:
      dockerfile: dev.dockerfile
    environment:
      DATABASE_URL: postgres://reddyt:reddyt@reddyt-database:5432/reddyt
    ports:
      - 8080:8080
    volumes:
      - ../:/home/dev/reddyt
      - reddyt-cargo-target:/home/dev/reddyt/target
      - reddyt-cargo-dist:/home/dev/reddyt/dist
    depends_on:
      - reddyt-database

  reddyt-database:
    container_name: reddyt_database
    image: postgres:18
    environment:
      POSTGRES_USER: reddyt
      POSTGRES_PASSWORD: reddyt
      POSTGRES_DB: reddyt
      PGDATA: /data/postgres
    ports:
      - "5432:5432"
    volumes:
      - reddyt-database:/data/postgres

volumes:
  reddyt-cargo-target:
  reddyt-cargo-dist:
  reddyt-database:
